FROM node:22.22.1-alpine3.23

RUN corepack enable && corepack prepare pnpm@11.24.0 --activate

WORKDIR /workspace

COPY repos/shared/package.json repos/shared/pnpm-lock.yaml ./repos/shared/
RUN pnpm --dir repos/shared install --prod --frozen-lockfile

COPY repos/server/package.json repos/server/pnpm-lock.yaml repos/server/pnpm-workspace.yaml ./repos/server/
RUN pnpm --dir repos/server install --frozen-lockfile

COPY repos/shared ./repos/shared
COPY repos/server ./repos/server

WORKDIR /workspace/repos/server

EXPOSE 3000

CMD ["sh", "-c", "CI=true pnpm install --frozen-lockfile && pnpm start:dev"]