FROM node:22.22.1-alpine3.23

RUN corepack enable && corepack prepare pnpm@11.24.0 --activate

WORKDIR /workspace

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "CI=true pnpm install --frozen-lockfile && pnpm start:dev"]